version: "3"

services:
  postgres-db-3:
    image: postgres:14.2-alpine
    container_name: postgres-db-3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=transactions
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    restart: always